# Generated by Django 5.1.3 on 2024-11-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_films_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
