# Generated by Django 5.1.3 on 2024-11-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_duration_film_duration_mins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='sypnosis',
        ),
    ]
