# Generated by Django 5.1.3 on 2024-11-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_film_sypnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='sypnosis',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
