# Generated by Django 5.1.3 on 2024-11-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_film_sypnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]),
        ),
        migrations.AlterField(
            model_name='film',
            name='status',
            field=models.CharField(choices=[('TO WATCH', 'TO WATCH'), ('WATCHING', 'WATCHING'), ('WATCHED', 'WATCHED'), ('REWATCHED', 'REWATCHED')], max_length=50),
        ),
    ]
