# Generated by Django 5.1.3 on 2024-11-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_film_rating_alter_film_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50),
        ),
    ]
